Add error message for missing option argument

diff --git a/files/home/.local/bin/pacman-du-top b/files/home/.local/bin/pacman-du-top
--- a/files/home/.local/bin/pacman-du-top
+++ b/files/home/.local/bin/pacman-du-top
@@ -24,6 +24,14 @@ while getopts ":n:h" option; do
         printf "%s\n" "$usage"
         exit 0
         ;;
+    :)
+        printf "Option missing argument: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
+    *)
+        printf "Invalid option: %s\n" "$OPTARG" >&2
+        exit 1
+        ;;
     esac
 done
 
