Tinkering

diff --git a/files/root/usr/local/sbin/mullvad-genkey b/files/root/usr/local/sbin/mullvad-genkey
--- a/files/root/usr/local/sbin/mullvad-genkey
+++ b/files/root/usr/local/sbin/mullvad-genkey
@@ -1,25 +1,37 @@
 #!/usr/bin/env bash
 
+# Generate and register a new WireGuard key with Mullvad.
+# Usage: mullvad-genkey ACCOUNT
+
 set -euo pipefail
 
-error() {
-    local format=$1
-    shift
-    printf "%s: line %d: $format\n" "$0" "${BASH_LINENO[0]}" "$@" >&2
-}
-
-die() {
-    error "$@"
+if [[ ! -v 1 ]]; then
+    printf "The first argument must be a 16-digit account number\n" >&2
     exit 1
-}
+fi
+
+if [[ ! $1 =~ ^[0-9]{16}$ ]]; then
+    printf "Invalid account number: %s (must be a 16-digit number)\n" "$1" >&2
+    exit 1
+fi
 
 account=$1
 
 private_key=$(wg genkey)
 public_key=$(wg pubkey <<<"$private_key")
 
-response=$(curl -sSL -d account="$account" --data-urlencode pubkey="$public_key" https://api.mullvad.net/wg/) || die "Unable to connect to Mullvad API"
-[[ $response =~ ^[0-9a-f:/.,]+$ ]] || die "$response"
+response=$(
+    curl --silent --show-error --location \
+        --data account="$account" \
+        --data-urlencode pubkey="$public_key" \
+        https://api.mullvad.net/wg/
+)
+
+if [[ ! $response =~ ^[0-9a-f:/.,]+$ ]]; then
+    printf "Unexpected response from Mullvad API: %s\n" "$response" >&2
+    exit 1
+fi
+
 address=$response
 
 config_file=/usr/local/etc/mullvad/client.conf
diff --git a/files/root/usr/local/sbin/mullvad-mkconfig b/files/root/usr/local/sbin/mullvad-mkconfig
--- a/files/root/usr/local/sbin/mullvad-mkconfig
+++ b/files/root/usr/local/sbin/mullvad-mkconfig
@@ -1,28 +1,38 @@
 #!/usr/bin/env bash
 
 # Generate WireGuard configuration files for Mullvad servers.
+# NOTE: This needs to be run any time there are new servers added.
 
 set -euo pipefail
 shopt -s nullglob
 
-error() {
-    local format=$1
-    shift
-    printf "%s: line %d: $format\n" "$0" "${BASH_LINENO[0]}" "$@" >&2
-}
+unset ADDRESS PRIVATE_KEY
 
-die() {
-    error "$@"
+client_config_file=/usr/local/etc/mullvad/client.conf
+
+if [[ ! -f $client_config_file || ! -r $client_config_file ]]; then
+    printf "File does not exist or is not readable: %q\n" "$client_config_file" >&2
     exit 1
-}
+fi
+
+if ! . "$client_config_file"; then
+    printf "Unable to source file: %q\n" "$client_config_file" >&2
+    exit 1
+fi
+
+for var in ADDRESS PRIVATE_KEY; do
+    if [[ ! -v $var || -z ${!var} ]]; then
+        printf "Invalid client configuration: %q (%s is not set)\n" "$client_config_file" "$var" >&2
+        exit 1
+    fi
+    export "$var=${!var}"
+done
+
+export DNS=193.138.218.74
 
 relays_file=/usr/local/share/mullvad/relays.json
-
 mkdir -p "$(dirname "$relays_file")"
-
-curl -sSL -o "$relays_file" \
-    https://api.mullvad.net/public/relays/wireguard/v1/ ||
-    die "Unable to connect to Mullvad API"
+curl -sSL -o "$relays_file" https://api.mullvad.net/public/relays/wireguard/v1/
 
 conf_template='[Interface]
 PrivateKey = $PRIVATE_KEY
@@ -34,24 +44,14 @@ PublicKey = $PUBLIC_KEY
 Endpoint = $ENDPOINT
 AllowedIPs = 0.0.0.0/0, ::/0'
 
-. /usr/local/etc/mullvad/client.conf
-
-: "$ADDRESS" "$PRIVATE_KEY"
-
-export ADDRESS PRIVATE_KEY
-export DNS=193.138.218.74
-
-wireguard_dir=/etc/wireguard
-
-mkdir -p "$wireguard_dir"
-
-rm -f "$wireguard_dir"/mullvad-*.conf
+wg_config_dir=/etc/wireguard
+mkdir -p "$wg_config_dir"
 
 umask 077
 
 while read -r hostname && read -r public_key && read -r ipv4_addr_in; do
-    conf_file=$wireguard_dir/mullvad-${hostname%-wireguard}.conf
+    conf_file=$wg_config_dir/mullvad-${hostname%-wireguard}.conf
     export PUBLIC_KEY=$public_key
     export ENDPOINT=$ipv4_addr_in:51820
     envsubst <<<"$conf_template" >"$conf_file"
-done < <(jq -r '.. | select(.hostname?) | .hostname, .public_key, .ipv4_addr_in' "$relays_file")
+done < <(jq -er '.. | select(.hostname?) | .hostname, .public_key, .ipv4_addr_in' "$relays_file")
diff --git a/files/root/usr/local/sbin/mullvad-select-relay b/files/root/usr/local/sbin/mullvad-select-relay
--- a/files/root/usr/local/sbin/mullvad-select-relay
+++ b/files/root/usr/local/sbin/mullvad-select-relay
@@ -4,21 +4,13 @@
 
 set -euo pipefail
 
-error() {
-    local format=$1
-    shift
-    printf "%s: line %s: $format\n" "$0" "${BASH_LINENO[0]}" "$@" >&2
-}
+location_config_file=/usr/local/etc/mullvad/location.conf
 
-die() {
-    error "$@"
+unset COUNTRY CITY
+
+if [[ -f $location_config_file ]] && ! . "$location_config_file"; then
+    printf "Unable to source file: %q\n" "$location_config_file" >&2
     exit 1
-}
-
-config_file=/usr/local/etc/mullvad/location.conf
-
-if [[ -f $config_file ]]; then
-    . "$config_file" || die "unable to source file: $config_file"
 fi
 
 declare -a jq_options=()
@@ -33,16 +25,20 @@ else
     jq_filter='.countries | map(.cities) | .[] | map(.relays) | flatten | map(.hostname) | .[]'
 fi
 
-interface=wg-mullvad
-config_dir=/etc/wireguard
-config_file=$config_dir/$interface.conf
+wg_interface=mullvad
+wg_config_dir=/etc/wireguard
+wg_config_file=$wg_config_dir/$wg_interface.conf
 
-relay_hostname=$(jq -r "${jq_options[@]}" "$jq_filter" /usr/local/share/mullvad/relays.json | shuf -n1)
+if ! relay_hostname=$(jq -er "${jq_options[@]}" "$jq_filter" /usr/local/share/mullvad/relays.json | shuf -n1) || [[ -z $relay_hostname ]]; then
+    printf "No relays found%s\n" "${COUNTRY:+ for location: $COUNTRY${CITY:+ $CITY}}" >&2
+    exit 1
+fi
 
-[[ -n $relay_hostname ]] || die "no relays found"
+relay_config_file=$wg_config_dir/mullvad-${relay_hostname%-wireguard}.conf
 
-relay_config_file=$config_dir/mullvad-${relay_hostname%-wireguard}.conf
+if [[ ! -f $relay_config_file || ! -r $relay_config_file ]]; then
+    printf "File does not exist or is not readable: %q\n" "$relay_config_file" >&2
+    exit 1
+fi
 
-[[ -f $relay_config_file ]] || die "configuration file does not exist: $relay_config_file"
-
-ln -svfn "$relay_config_file" "$config_file"
+ln -vsfn "$relay_config_file" "$wg_config_file"
